// Generated by gencpp from file msg_tester/Angle.msg
// DO NOT EDIT!


#ifndef MSG_TESTER_MESSAGE_ANGLE_H
#define MSG_TESTER_MESSAGE_ANGLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_tester
{
template <class ContainerAllocator>
struct Angle_
{
  typedef Angle_<ContainerAllocator> Type;

  Angle_()
    : des_angle(0)  {
    }
  Angle_(const ContainerAllocator& _alloc)
    : des_angle(0)  {
  (void)_alloc;
    }



   typedef uint32_t _des_angle_type;
  _des_angle_type des_angle;





  typedef boost::shared_ptr< ::msg_tester::Angle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_tester::Angle_<ContainerAllocator> const> ConstPtr;

}; // struct Angle_

typedef ::msg_tester::Angle_<std::allocator<void> > Angle;

typedef boost::shared_ptr< ::msg_tester::Angle > AnglePtr;
typedef boost::shared_ptr< ::msg_tester::Angle const> AngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_tester::Angle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_tester::Angle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_tester::Angle_<ContainerAllocator1> & lhs, const ::msg_tester::Angle_<ContainerAllocator2> & rhs)
{
  return lhs.des_angle == rhs.des_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_tester::Angle_<ContainerAllocator1> & lhs, const ::msg_tester::Angle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_tester

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msg_tester::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_tester::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_tester::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_tester::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_tester::Angle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_tester::Angle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_tester::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b014ad599de74f65dbbbb8e4f583b3d";
  }

  static const char* value(const ::msg_tester::Angle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b014ad599de74f6ULL;
  static const uint64_t static_value2 = 0x5dbbbb8e4f583b3dULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_tester::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_tester/Angle";
  }

  static const char* value(const ::msg_tester::Angle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_tester::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 des_angle\n"
;
  }

  static const char* value(const ::msg_tester::Angle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_tester::Angle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.des_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Angle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_tester::Angle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_tester::Angle_<ContainerAllocator>& v)
  {
    s << indent << "des_angle: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.des_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_TESTER_MESSAGE_ANGLE_H
